### ISSUE TITLE
Is the name of events in the readme wrong?

### ISSUE THREAD

**Issue by Deanwfy** [bryik/aframe-cubemap-component#34]
### Events

|       Name        |                 Description                 |
| :---------------: | :-----------------------------------------: |
| cubeTextureLoaded | Emitted when a texture has finished loading |

cubeTextureLoaded seems to be cubemapLoaded?

**Comment by bryik** [comment]
Yep, you are correct. 

The event name is ["cubemapLoaded"](https://github.com/bryik/aframe-cubemap-component/blob/master/index.js#L144) and IIRC was called ["cubemapLoaded" when the event was first added](https://github.com/bryik/aframe-cubemap-component/commit/27ef4f74ad251815ff1bda923ebadb57e03efe54#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346). So this looks to be an unfortunate mistake in the README, thanks for bringing it to my attention (fixed in https://github.com/bryik/aframe-cubemap-component/commit/40f68b69ce3ab7e43788d8baf37a369a81de3bd3).
